// Created by John Åkerblom 2014-11-22

#include "../h3mlib.h"
#include "parse_oa.h"
#include "../utils/safe_read.h"

#include "../meta/meta_object.h"

#include "../gen/def_bodies_array.h"

#include "../h3m_constants/h3m_oa_class.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#ifdef _MSC_VER
#pragma warning(disable:4996)   // M$ standard lib unsafe
#endif

static int _oa_type_from_constants(uint32_t object_class,
    uint32_t object_number, uint8_t object_group)
{
    // defines missing in VCMI :-)
    // TODO merge these and h3m_oa_class.h
#define H3M_OA_CLASS_DECORATIVE_TOWN 1      // Observed "decorative" Fortress on map "West Orient & Underground Cave" use this
#define H3M_OA_CLASS_MARKET_OF_TIME 50

#define H3M_OA_CLASS_IMPASSABLE_TERRAIN1 116
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN2 118
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN3 119
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN4 120
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN5 121
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN6 126
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN7 127
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN8 130
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN9 131
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN10 133
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN11 134
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN12 135
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN13 136
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN14 137
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN15 143
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN16 147
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN17 148
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN18 149
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN19 150
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN20 151
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN21 153
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN22 155
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN23 158
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN24 161
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN25 128
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN26 129
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN27 117
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN28 132

#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD1 199
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD2 206
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD3 207
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD4 208
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD5 209
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD6 210
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD7 211
#define H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD8 177

#define H3M_OA_CLASS_KELP 125
#define H3M_OA_CLASS_WOG1 40        // ZRain00

    switch (object_class) {
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN1:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN2:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN3:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN4:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN5:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN6:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN7:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN8:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN9:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN10:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN11:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN12:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN13:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN14:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN15:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN16:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN17:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN18:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN19:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN20:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN21:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN22:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN23:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN24:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN25:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN26:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN27:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN28:
        return META_OBJECT_GENERIC_IMPASSABLE_TERRAIN;
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD1:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD2:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD3:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD4:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD5:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD6:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD7:
    case H3M_OA_CLASS_IMPASSABLE_TERRAIN_ABSOD8:
        return META_OBJECT_GENERIC_IMPASSABLE_TERRAIN_ABSOD;
    case H3M_OA_CLASS_WOG1:        // TODO when better WoG support is had adjust this
        return META_OBJECT_GENERIC_VISITABLE_ABSOD;
    case H3M_OA_CLASS_ALTAR_OF_SACRIFICE:
    case H3M_OA_CLASS_ANCHOR_POINT:
    case H3M_OA_CLASS_ARENA:
    case H3M_OA_CLASS_BLACK_MARKET:
    case H3M_OA_CLASS_CARTOGRAPHER:
    case H3M_OA_CLASS_BUOY:
    case H3M_OA_CLASS_SWAN_POND:
    case H3M_OA_CLASS_COVER_OF_DARKNESS:
    case H3M_OA_CLASS_CREATURE_BANK:
    case H3M_OA_CLASS_CORPSE:
    case H3M_OA_CLASS_MARLETTO_TOWER:
    case H3M_OA_CLASS_DERELICT_SHIP:
    case H3M_OA_CLASS_DRAGON_UTOPIA:
    case H3M_OA_CLASS_EYE_OF_MAGI:
    case H3M_OA_CLASS_FAERIE_RING:
    case H3M_OA_CLASS_FOUNTAIN_OF_FORTUNE:
    case H3M_OA_CLASS_FOUNTAIN_OF_YOUTH:
    case H3M_OA_CLASS_GARDEN_OF_REVELATION:
    case H3M_OA_CLASS_HILL_FORT:
    case H3M_OA_CLASS_HUT_OF_MAGI:
    case H3M_OA_CLASS_IDOL_OF_FORTUNE:
    case H3M_OA_CLASS_LEAN_TO:
    case H3M_OA_CLASS_LIBRARY_OF_ENLIGHTENMENT:

    case H3M_OA_CLASS_SCHOOL_OF_MAGIC:
    case H3M_OA_CLASS_MAGIC_SPRING:
    case H3M_OA_CLASS_MAGIC_WELL:
    case H3M_OA_CLASS_MERCENARY_CAMP:
    case H3M_OA_CLASS_MERMAID:
    case H3M_OA_CLASS_MYSTICAL_GARDEN:
    case H3M_OA_CLASS_OASIS:
    case H3M_OA_CLASS_OBELISK:
    case H3M_OA_CLASS_REDWOOD_OBSERVATORY:
    case H3M_OA_CLASS_PILLAR_OF_FIRE:
    case H3M_OA_CLASS_STAR_AXIS:
    case H3M_OA_CLASS_RALLY_FLAG:
    case H3M_OA_CLASS_BORDERGUARD:
    case H3M_OA_CLASS_KEYMASTER:
    case H3M_OA_CLASS_REFUGEE_CAMP:
    case H3M_OA_CLASS_SANCTUARY:
    case H3M_OA_CLASS_CRYPT:
    case H3M_OA_CLASS_SHIPWRECK:
    case H3M_OA_CLASS_SIRENS:
    case H3M_OA_CLASS_STABLES:
    case H3M_OA_CLASS_TAVERN:
    case H3M_OA_CLASS_TEMPLE:
    case H3M_OA_CLASS_DEN_OF_THIEVES:
    case H3M_OA_CLASS_TRADING_POST:
    case H3M_OA_CLASS_LEARNING_STONE:
    case H3M_OA_CLASS_TREE_OF_KNOWLEDGE:
    case H3M_OA_CLASS_UNIVERSITY:
    case H3M_OA_CLASS_WAGON:
    case H3M_OA_CLASS_WAR_MACHINE_FACTORY:
    case H3M_OA_CLASS_SCHOOL_OF_WAR:
    case H3M_OA_CLASS_WARRIORS_TOMB:
    case H3M_OA_CLASS_WATER_WHEEL:
    case H3M_OA_CLASS_WATERING_HOLE:
    case H3M_OA_CLASS_WHIRLPOOL:
    case H3M_OA_CLASS_WINDMILL:
    case H3M_OA_CLASS_MARKET_OF_TIME:
    case H3M_OA_CLASS_DECORATIVE_TOWN:
        return META_OBJECT_GENERIC_VISITABLE;
    case H3M_OA_CLASS_TRADING_POST_SNOW:
    case H3M_OA_CLASS_PYRAMID:     // TODO actually this is a WoG object, so move/refactor 
    case H3M_OA_CLASS_BORDER_GATE:
    case H3M_OA_CLASS_FREELANCERS_GUILD:
        return META_OBJECT_GENERIC_VISITABLE_ABSOD;
    case H3M_OA_CLASS_ARTIFACT:
    case H3M_OA_CLASS_RANDOM_ART:
    case H3M_OA_CLASS_RANDOM_TREASURE_ART:
    case H3M_OA_CLASS_RANDOM_MINOR_ART:
    case H3M_OA_CLASS_RANDOM_MAJOR_ART:
    case H3M_OA_CLASS_RANDOM_RELIC_ART:
        return META_OBJECT_ARTIFACT;
    case H3M_OA_CLASS_ABANDONED_MINE:      // TODO check object_number
        return META_OBJECT_ABANDONED_MINE_ABSOD;
    case H3M_OA_CLASS_CREATURE_GENERATOR1:
    case H3M_OA_CLASS_CREATURE_GENERATOR2:
    case H3M_OA_CLASS_CREATURE_GENERATOR3:
    case H3M_OA_CLASS_CREATURE_GENERATOR4:
        return META_OBJECT_DWELLING;
    case H3M_OA_CLASS_EVENT:
        return META_OBJECT_EVENT;
    case H3M_OA_CLASS_GARRISON:
        return META_OBJECT_GARRISON;
    case H3M_OA_CLASS_GARRISON2:
        return META_OBJECT_GARRISON_ABSOD;
    case H3M_OA_CLASS_BOAT:
        return META_OBJECT_GENERIC_BOAT;
    case H3M_OA_CLASS_CLOVER_FIELD:
    case H3M_OA_CLASS_EVIL_FOG:
    case H3M_OA_CLASS_FAVORABLE_WINDS:
    case H3M_OA_CLASS_FIERY_FIELDS:
    case H3M_OA_CLASS_HOLY_GROUNDS:
    case H3M_OA_CLASS_LUCID_POOLS:
    case H3M_OA_CLASS_MAGIC_CLOUDS:
    case H3M_OA_CLASS_ROCKLANDS:
    case H3M_OA_CLASS_CURSED_GROUND2:
    case H3M_OA_CLASS_MAGIC_PLAINS2:
        return META_OBJECT_GENERIC_PASSABLE_TERRAIN_SOD;
    case H3M_OA_CLASS_HOLE:
    case H3M_OA_CLASS_CURSED_GROUND1:
    case H3M_OA_CLASS_MAGIC_PLAINS1:
    case H3M_OA_CLASS_KELP:
        return META_OBJECT_GENERIC_PASSABLE_TERRAIN;
    case H3M_OA_CLASS_PANDORAS_BOX:
        return META_OBJECT_PANDORAS_BOX;
    case H3M_OA_CLASS_GRAIL:
        return META_OBJECT_GRAIL;
    case H3M_OA_CLASS_HERO:
        return META_OBJECT_HERO;
    case H3M_OA_CLASS_LIGHTHOUSE:
        return META_OBJECT_LIGHTHOUSE;
    case H3M_OA_CLASS_MONOLITH_TWO_WAY:    // TODO once monoliths have been divided fix this
        //return META_OBJECTMONOLITH_TWO_WAY;
    case H3M_OA_CLASS_MONOLITH_ONE_WAY_ENTRANCE:
    case H3M_OA_CLASS_MONOLITH_ONE_WAY_EXIT:
        return META_OBJECT_GENERIC_VISITABLE_ABSOD;
    case H3M_OA_CLASS_MONSTER:
    case H3M_OA_CLASS_RANDOM_MONSTER:
    case H3M_OA_CLASS_RANDOM_MONSTER_L1:
    case H3M_OA_CLASS_RANDOM_MONSTER_L2:
    case H3M_OA_CLASS_RANDOM_MONSTER_L3:
    case H3M_OA_CLASS_RANDOM_MONSTER_L4:
    case H3M_OA_CLASS_RANDOM_MONSTER_L5:
    case H3M_OA_CLASS_RANDOM_MONSTER_L6:
    case H3M_OA_CLASS_RANDOM_MONSTER_L7:
        return META_OBJECT_MONSTER;
    case H3M_OA_CLASS_OCEAN_BOTTLE:
        return META_OBJECT_OCEAN_BOTTLE;
    case H3M_OA_CLASS_PRISON:
        return META_OBJECT_PRISON;
    case H3M_OA_CLASS_QUEST_GUARD:
        return META_OBJECT_QUEST_GUARD;
    case H3M_OA_CLASS_RANDOM_DWELLING:
        return META_OBJECT_RANDOM_DWELLING_ABSOD;
    case H3M_OA_CLASS_RANDOM_DWELLING_LVL:
        return META_OBJECT_RANDOM_DWELLING_PRESET_LEVEL_ABSOD;
    case H3M_OA_CLASS_RANDOM_DWELLING_FACTION:
        return META_OBJECT_RANDOM_DWELLING_PRESET_ALIGNMENT_ABSOD;
    case H3M_OA_CLASS_RANDOM_HERO:
        return META_OBJECT_RANDOM_HERO;
    case H3M_OA_CLASS_HERO_PLACEHOLDER:
        return META_OBJECT_PLACEHOLDER_HERO;
    case H3M_OA_CLASS_RESOURCE:
    case H3M_OA_CLASS_RANDOM_RESOURCE:
        return META_OBJECT_RESOURCE;
    case H3M_OA_CLASS_MINE:
        return META_OBJECT_RESOURCE_GENERATOR;
    case H3M_OA_CLASS_SCHOLAR:
        return META_OBJECT_SCHOLAR;
    case H3M_OA_CLASS_SEER_HUT:
        return META_OBJECT_SEERS_HUT;
    case H3M_OA_CLASS_SHIPYARD:
        return META_OBJECT_SHIPYARD;
    case H3M_OA_CLASS_SHRINE_OF_MAGIC_INCANTATION:
    case H3M_OA_CLASS_SHRINE_OF_MAGIC_GESTURE:
    case H3M_OA_CLASS_SHRINE_OF_MAGIC_THOUGHT:
        return META_OBJECT_SHRINE;
    case H3M_OA_CLASS_SIGN:
        return META_OBJECT_SIGN;
    case H3M_OA_CLASS_SPELL_SCROLL:
        return META_OBJECT_SPELL_SCROLL;
    case H3M_OA_CLASS_SUBTERRANEAN_GATE:
        return META_OBJECT_SUBTERRANEAN_GATE;
    case H3M_OA_CLASS_TOWN:
    case H3M_OA_CLASS_RANDOM_TOWN:
        return META_OBJECT_TOWN;
    case H3M_OA_CLASS_WITCH_HUT:
        return META_OBJECT_WITCH_HUT;
    case H3M_OA_CLASS_CAMPFIRE:
    case H3M_OA_CLASS_FLOTSAM:
    case H3M_OA_CLASS_SEA_CHEST:
    case H3M_OA_CLASS_SHIPWRECK_SURVIVOR:
    case H3M_OA_CLASS_TREASURE_CHEST:
        return META_OBJECT_GENERIC_TREASURE;
    default:
        break;
    }

    return -1;
}

int parse_oa_meta_type(struct H3M_OA_ENTRY *oa_entry, int *meta_type,
    int *is_custom, h3m_custom_def_cb_t cb, void *cb_data)
{
    int val = 0;

    *is_custom = 0;
#if 0
    // Custom check
    if (NULL != cb && -1 != (val = cb(oa_entry->header.def, cb_data))) {
        *meta_type = val;
        *is_custom = 1;
        return 0;
    }
#endif

    // OA's constants check
    if (-1 != (val =
            _oa_type_from_constants(oa_entry->body.object_class,
                oa_entry->body.object_number, oa_entry->body.object_group))) {
        //val = _oa_type_version_adjust(val, oa_entry->header.def, oa_entry->body.object_number);

        *meta_type = val;
        return 0;
    }

    *meta_type = -1;
    return -1;
}
