// Created by John Åkerblom 2015-12-16

#ifndef __H3M_TERRAIN_H_DEF__
#define __H3M_TERRAIN_H_DEF__

enum H3M_TERRAIN {
    H3M_TERRAIN_DIRT,
    H3M_TERRAIN_SAND,
    H3M_TERRAIN_GRASS,
    H3M_TERRAIN_SNOW,
    H3M_TERRAIN_SWAMP,
    H3M_TERRAIN_ROUGH,
    H3M_TERRAIN_SUBTERRANEAN,
    H3M_TERRAIN_LAVA,
    H3M_TERRAIN_WATER,
    H3M_TERRAIN_ROCK
};

#endif
